# Generated by Django 3.2.9 on 2022-06-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel_name', models.CharField(max_length=57, unique=True, verbose_name='hostel name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20, verbose_name='gender')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
            ],
            options={
                'verbose_name_plural': 'Hostels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=26, verbose_name='room name')),
                ('room_type', models.CharField(choices=[('Single Occupancy', 'Single Occupancy'), ('Shared Occupancy', 'Shared Occupancy'), ('Reserved Occupancy', 'Reserved Occupancy')], default='Shared Occupancy', max_length=26, verbose_name='room type')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_name', models.CharField(help_text='eg. space 1, space 2,...', max_length=26, verbose_name='space name')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('vacant', models.BooleanField(default=False, verbose_name='vacant')),
                ('reserved', models.BooleanField(default=False, verbose_name='reserved')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.rooms')),
            ],
            options={
                'verbose_name_plural': 'Spaces',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HostelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateTimeField(null=True, verbose_name='checkin date')),
                ('checkout_date', models.DateTimeField(null=True, verbose_name='checkout date')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('cleared', models.BooleanField(default=False, help_text='student should be cleared before checking out', verbose_name='cleared')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hostel.space')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Hostel Booking',
                'ordering': ['-id'],
            },
        ),
    ]
