# Generated by Django 3.2.9 on 2022-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_space_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='vacant',
            field=models.BooleanField(default=True, verbose_name='vacant'),
        ),
    ]
